// scripts/seed.js — Seed demo data into JSON database
// Run: node scripts/seed.js

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const DATA_DIR = path.join(__dirname, '..', 'data');
if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });

function hash(pw) {
  return crypto.createHmac('sha256', process.env.JWT_SECRET||'bandhan_default_secret').update(pw).digest('hex');
}

const USERS = [
  { id:'u001', name:'Priya Sharma', email:'priya@example.com', password:hash('demo123'), phone:'9876543210', dob:'1998-03-15', gender:'Female', religion:'Hindu', caste:'Brahmin', city:'Chennai', state:'Tamil Nadu', country:'India', mother_tongue:'Tamil', languages:['Tamil','English'], marital_status:'Never Married', education_level:'Post Graduate', education_field:'Computer Science', profession:'Software Engineer', company:'TechCorp', income_range:'12-15 LPA', diet:'Vegetarian', smoking:'Never', drinking:'Never', height_cm:163, family_type:'Nuclear', family_values:'Moderate', hobbies:['Reading','Classical Music','Travelling'], values:['Family-Oriented','Health-Conscious','Avid Reader'], about:'Looking for a kind, ambitious partner who values family and personal growth. I believe great relationships are built on trust, laughter and shared dreams.', partner_preference:{ age_min:26, age_max:34, religions:['Hindu'], deal_breakers:['no_smoking'] }, photos:[], verified:true, trust_score:94, profile_complete_pct:92, subscription:{ plan:'plus', status:'active' }, active:true, deleted:false, is_suspended:false, is_admin:false, last_active:new Date().toISOString(), created_at:'2025-01-10T00:00:00.000Z' },
  { id:'u002', name:'Arjun Mehta', email:'arjun@example.com', password:hash('demo123'), phone:'9876500001', dob:'1996-07-22', gender:'Male', religion:'Hindu', caste:'Brahmin', city:'Pune', state:'Maharashtra', country:'India', mother_tongue:'Hindi', languages:['Hindi','English','Marathi'], marital_status:'Never Married', education_level:'Post Graduate', education_field:'Technology', profession:'Software Engineer', company:'InnoSoft', income_range:'18-22 LPA', diet:'Non-Vegetarian', smoking:'Never', drinking:'Occasionally', height_cm:178, family_type:'Nuclear', family_values:'Moderate', hobbies:['Travel','Fitness','Cooking','Cricket'], values:['Tech-Enthusiast','Traveller','Family'], about:'Tech enthusiast who loves building things. I travel when I can, cook on weekends, and believe in deep conversations over small talk.', partner_preference:{ age_min:24, age_max:30, religions:['Hindu','Any'], deal_breakers:[] }, photos:[], verified:true, trust_score:91, profile_complete_pct:88, subscription:{ plan:'plus', status:'active' }, active:true, deleted:false, is_suspended:false, is_admin:false, last_active:new Date().toISOString(), created_at:'2025-01-15T00:00:00.000Z' },
  { id:'u003', name:'Meera Iyer', email:'meera@example.com', password:hash('demo123'), phone:'9876500002', dob:'1999-11-08', gender:'Female', religion:'Hindu', caste:'Iyer', city:'Bangalore', state:'Karnataka', country:'India', mother_tongue:'Tamil', languages:['Tamil','Kannada','English'], marital_status:'Never Married', education_level:'Post Graduate', education_field:'Business Administration', profession:'Business Analyst', company:'Analytics Co', income_range:'10-12 LPA', diet:'Vegetarian', smoking:'Never', drinking:'Never', height_cm:160, family_type:'Joint', family_values:'Traditional', hobbies:['Classical Music','Reading','Art'], values:['Classical Music','Reading','Culture'], about:'Music lover and bookworm. Simple living, high thinking. I find beauty in simplicity and believe that good conversation is the best adventure.', partner_preference:{ age_min:26, age_max:32, religions:['Hindu'], deal_breakers:['no_smoking','no_drinking'] }, photos:[], verified:true, trust_score:96, profile_complete_pct:85, subscription:{ plan:'free', status:'active' }, active:true, deleted:false, is_suspended:false, is_admin:false, last_active:new Date().toISOString(), created_at:'2025-02-01T00:00:00.000Z' },
  { id:'u004', name:'Rahul Verma', email:'rahul@example.com', password:hash('demo123'), phone:'9876500003', dob:'1994-04-12', gender:'Male', religion:'Hindu', caste:'Yadav', city:'Delhi', state:'Delhi', country:'India', mother_tongue:'Hindi', languages:['Hindi','English'], marital_status:'Never Married', education_level:'Doctorate', education_field:'Medicine', profession:'Doctor', company:'AIIMS Delhi', income_range:'25-30 LPA', diet:'Non-Vegetarian', smoking:'Never', drinking:'Never', height_cm:175, family_type:'Joint', family_values:'Traditional', hobbies:['Cooking','Spirituality','Cricket','Travel'], values:['Healthcare','Family','Spirituality','Cooking'], about:'A doctor by profession, a foodie by passion. I believe family is everything and looking for someone who values the same.', partner_preference:{ age_min:24, age_max:30, religions:['Hindu','Any'], deal_breakers:['no_smoking'] }, photos:[], verified:true, trust_score:98, profile_complete_pct:97, subscription:{ plan:'parivar', status:'active' }, active:true, deleted:false, is_suspended:false, is_admin:false, last_active:new Date().toISOString(), created_at:'2025-01-20T00:00:00.000Z' },
  { id:'u005', name:'Ananya Reddy', email:'ananya@example.com', password:hash('demo123'), phone:'9876500004', dob:'1997-09-30', gender:'Female', religion:'Hindu', caste:'Reddy', city:'Hyderabad', state:'Telangana', country:'India', mother_tongue:'Telugu', languages:['Telugu','Hindi','English'], marital_status:'Never Married', education_level:'Post Graduate', education_field:'Finance', profession:'Chartered Accountant', company:'Deloitte', income_range:'15-18 LPA', diet:'Non-Vegetarian', smoking:'Never', drinking:'Occasionally', height_cm:165, family_type:'Nuclear', family_values:'Moderate', hobbies:['Travel','Food','Fitness','Photography'], values:['Independence','Finance','Travel','Food'], about:'Independent and grounded. Love exploring new places and cuisines. Looking for a mature partner who gives space and values individual growth.', partner_preference:{ age_min:27, age_max:36, religions:['Hindu','Any'], deal_breakers:[] }, photos:[], verified:true, trust_score:89, profile_complete_pct:90, subscription:{ plan:'plus', status:'active' }, active:true, deleted:false, is_suspended:false, is_admin:false, last_active:new Date().toISOString(), created_at:'2025-02-10T00:00:00.000Z' },
  { id:'u006', name:'Vikram Nair', email:'vikram@example.com', password:hash('demo123'), phone:'9876500005', dob:'1995-06-18', gender:'Male', religion:'Hindu', caste:'Nair', city:'Kochi', state:'Kerala', country:'India', mother_tongue:'Malayalam', languages:['Malayalam','English','Hindi'], marital_status:'Never Married', education_level:'Graduate', education_field:'Education', profession:'School Teacher', company:'DPS Kochi', income_range:'5-8 LPA', diet:'Non-Vegetarian', smoking:'Never', drinking:'Never', height_cm:173, family_type:'Joint', family_values:'Traditional', hobbies:['Nature','Trekking','Reading','Photography'], values:['Education','Nature','Simplicity','Trekking'], about:'Passionate educator who believes in shaping futures. I find joy in nature, long treks, and evening conversations by the sea.', partner_preference:{ age_min:23, age_max:29, religions:['Hindu'], deal_breakers:['no_smoking'] }, photos:[], verified:true, trust_score:92, profile_complete_pct:82, subscription:{ plan:'free', status:'active' }, active:true, deleted:false, is_suspended:false, is_admin:false, last_active:new Date().toISOString(), created_at:'2025-03-01T00:00:00.000Z' },
  { id:'u007', name:'Sunita Patel', email:'sunita@example.com', password:hash('demo123'), phone:'9876500006', dob:'1992-12-25', gender:'Female', religion:'Hindu', caste:'Patel', city:'Ahmedabad', state:'Gujarat', country:'India', mother_tongue:'Gujarati', languages:['Gujarati','Hindi','English'], marital_status:'Divorced', education_level:'Post Graduate', education_field:'Business', profession:'Business Owner', company:'Own Business', income_range:'20-25 LPA', diet:'Vegetarian', smoking:'Never', drinking:'Never', height_cm:163, family_type:'Nuclear', family_values:'Moderate', hobbies:['Travel','Dogs','Entrepreneurship','Yoga'], values:['Resilience','Entrepreneurship','Travel','Independence'], about:'Life taught me resilience. I rebuilt myself and now ready for a new chapter with someone mature, kind and understanding.', partner_preference:{ age_min:30, age_max:45, religions:['Any'], deal_breakers:[] }, photos:[], verified:true, trust_score:87, profile_complete_pct:88, subscription:{ plan:'plus', status:'active' }, active:true, deleted:false, is_suspended:false, is_admin:false, last_active:new Date().toISOString(), created_at:'2025-03-15T00:00:00.000Z' },
  { id:'u008', name:'Karthik Subramanian', email:'karthik@example.com', password:hash('demo123'), phone:'9876500007', dob:'1993-02-14', gender:'Male', religion:'Hindu', caste:'Mudaliar', city:'Singapore', state:'NRI', country:'Singapore', mother_tongue:'Tamil', languages:['Tamil','English'], marital_status:'Never Married', education_level:'Post Graduate', education_field:'Computer Science', profession:'Data Scientist', company:'Google Singapore', income_range:'50+ LPA', diet:'Non-Vegetarian', smoking:'Never', drinking:'Occasionally', height_cm:180, family_type:'Nuclear', family_values:'Moderate', hobbies:['Technology','Cricket','Food','Culture'], values:['Technology','Culture','Food','Cricket'], about:'NRI in Singapore who misses home. Looking for someone rooted in Indian values who can match my curiosity and love for life.', partner_preference:{ age_min:26, age_max:33, religions:['Hindu'], deal_breakers:['no_smoking'] }, photos:[], verified:true, trust_score:95, profile_complete_pct:94, subscription:{ plan:'parivar', status:'active' }, active:true, deleted:false, is_suspended:false, is_admin:false, last_active:new Date().toISOString(), created_at:'2025-01-05T00:00:00.000Z' },
  // Admin user
  { id:'admin001', name:'Admin Bandhan', email:'admin@bandhan.app', password:hash('Admin@2025!'), phone:'9999999999', gender:'Male', religion:'Hindu', city:'Mumbai', state:'Maharashtra', country:'India', mother_tongue:'Hindi', languages:['Hindi','English'], marital_status:'Never Married', education_level:'Post Graduate', profession:'Admin', photos:[], verified:true, trust_score:100, profile_complete_pct:100, subscription:{ plan:'elite', status:'active' }, active:true, deleted:false, is_suspended:false, is_admin:true, last_active:new Date().toISOString(), created_at:'2025-01-01T00:00:00.000Z' },
];

const INTERESTS = [
  { id:'i001', from_user:'u004', to_user:'u001', status:'pending', message:'Hi! I think we have a lot in common.', created_at:'2025-04-11T10:00:00.000Z' },
  { id:'i002', from_user:'u008', to_user:'u001', status:'pending', message:'Saw your profile — we share similar values!', created_at:'2025-04-12T14:00:00.000Z' },
  { id:'i003', from_user:'u001', to_user:'u002', status:'pending', message:'Your profile caught my attention!', created_at:'2025-04-10T09:00:00.000Z' },
];

const MESSAGES = [
  { id:'m001', from_user:'u004', to_user:'u001', text:'Hello Priya! Are you currently in Chennai?', type:'text', read:true, flagged:false, created_at:'2025-04-11T10:30:00.000Z' },
  { id:'m002', from_user:'u001', to_user:'u004', text:'Hi Rahul! Yes I am. What about you?', type:'text', read:true, flagged:false, created_at:'2025-04-11T11:00:00.000Z' },
  { id:'m003', from_user:'u004', to_user:'u001', text:'In Delhi, but open to relocate for the right reason 😊', type:'text', read:false, flagged:false, created_at:'2025-04-11T11:30:00.000Z' },
];

const CONFIG = {
  languages: ['Hindi','Tamil','Telugu','Kannada','Malayalam','Marathi','Gujarati','Bengali','Punjabi','Odia','Urdu','Assamese','Konkani','Sindhi','Kashmiri','Nepali','Bodo','Sanskrit','English','Maithili'],
  religions: ['Hindu','Muslim','Christian','Sikh','Jain','Buddhist','Parsi','Jewish','Any'],
  marital_statuses: ['Never Married','Divorced','Widowed','Awaiting Divorce'],
  income_ranges: ['Below 3 LPA','3-5 LPA','5-8 LPA','8-12 LPA','12-15 LPA','15-20 LPA','20-30 LPA','30-50 LPA','50+ LPA'],
  education_levels: ['High School','Diploma','Graduate','Post Graduate','Doctorate','Other'],
  family_types: ['Nuclear','Joint','Extended'],
  family_values: ['Orthodox','Traditional','Moderate','Liberal'],
};

// Write all files
const write = (name, data) => {
  fs.writeFileSync(path.join(DATA_DIR, `${name}.json`), JSON.stringify(data, null, 2));
  console.log(`  ✅  ${name}.json — ${Array.isArray(data) ? data.length + ' records' : 'config'}`);
};

console.log('\n  💍  Seeding Bandhan database...\n');
write('users', USERS);
write('interests', INTERESTS);
write('messages', MESSAGES);
write('reports', []);
write('config', CONFIG);
console.log('\n  🎉  Done! Database seeded successfully.');
console.log('  📧  Demo login: priya@example.com / demo123');
console.log('  👑  Admin login: admin@bandhan.app / Admin@2025!\n');
